server:
  port: 9296

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/siddharth8899/config-server
          clone-on-start: true
